### ISSUE TITLE
When open source the code

### ISSUE THREAD

**Issue by lei1993** [uci-cbcl/NoduleNet#1]
Nice work, when open-source the code?

**Comment by tanghaotommy** [comment]
Thanks for your interest. We are currently working actively on finalizing the source code. We intend to have our full code out before the MICCAI conference (Oct 13th).

**Comment by MENG1996** [comment]
I'm waiting for your code~~~

**Comment by tanghaotommy** [comment]
Sorry for the delay and thanks for your interest. We have now made the code public available for non-commercial research purpose only.
