### ISSUE TITLE
Training Data Problems

### ISSUE THREAD

**Issue by Amadeuszhao** [uci-cbcl/NoduleNet#10]
Recently, when I tried to reproduce the result of your work(https://github.com/uci-cbcl/NoduleNet) , I encounted some issues.
I modified your code and then followed your instruction step by step.
And here’s the problem
![image](https://user-images.githubusercontent.com/48089895/72710295-bf17c180-3ba1-11ea-9ccb-5ce3537f79bf.png)
As you can see there are 3498 files under the preprocess_data folder  after I followed your preprocess instruction
However when I strared training,
![image](https://user-images.githubusercontent.com/48089895/72710398-fe461280-3ba1-11ea-8461-deab2a55edfe.png)

There are only 62 training loaders, is this normal?
At your convenience, would you please give me some of your insights.
Thank you, I will appreciate it a lot.

**Comment by tanghaotommy** [comment]
Yes, it is normal. Each training loader iteration uses batch of images as input. The default batch size is set to 16, so each train iteration uses 16*62=992 nodules

**Comment by Amadeuszhao** [comment]
> Yes, it is normal. Each training loader iteration uses batch of images as input. The default batch size is set to 16, so each train iteration uses 16*62=992 nodules

But I suppose the whole LUNA datasets have mode nodules.
