### ISSUE TITLE
Is it possible to share a trained model?

### ISSUE THREAD

**Issue by wenyalintw** [uci-cbcl/NoduleNet#11]
Hello developer!
First of all, thanks for sharing your code,  I truly appreciate your generosity.
I'm trying to reproduce your work lately but not success yet.
I'm wonder if you could share a trained model? Definitely for non-commercial use only.

If sharing through email is preferred, below is my email account, thanks a lot anyway!
wenyalintw@gmail.com

**Comment by wenyalintw** [comment]
I train the model on one GeForce GTX 1060 6GB, which could only handle batchsize=2, not sure if this is why I couldn't train the model successfully.

For who have trouble installing build/box, I change all "long" to "int64_t" in nms.cpp to install it successfully on win10. (still lots of warning about data type when installing, not sure if it is important.)

**Comment by tanghaotommy** [comment]
Sorry for the delay. I will share a pertained weight shortly

**Comment by tanghaotommy** [comment]
https://drive.google.com/file/d/1B2aB_4HTw5OEe8jH6XPoQYRJw4hGuDXD/view?usp=sharing
Please let me know if it does not work

**Comment by valbertoenoc** [comment]
@wenyalintw 
Could you please let us know how did you go about compiling build/box on windows?
Thanks!
