### ISSUE TITLE
dataset details

### ISSUE THREAD

**Issue by czifan** [uci-cbcl/NoduleNet#13]
Thanks for the open source code, which is so helpful for me!
But I have a question about the dataset. I found that "resulting in a total number of 586 CT scans with 1131 nodules" in section "3 Result - Data and experiment configurations" of your paper. But I noticed that there are only 583 CT scans in the split folder in this code. In addition, I have preprocessed the data by following this readme.md and I only have 583 CT scans. Is the results in the paper on this dataset of this code? Because it will be a baseline for comparison and this question is important. Thank you!!!

**Comment by tanghaotommy** [comment]
Thanks for your interest. 

It is the code for this paper. I took a look and it seems the code indeed generates 583 CTs. I will look into this problem and figure out which number is correct.

**Comment by czifan** [comment]
Thanks for your reply!
Could you tell me the result of the problem if you solve it?

**Comment by huliangxiao** [comment]
Thank you so much for the code!
I have the same problem as @czifan, please let us know when it's settled.

**Comment by tanghaotommy** [comment]
Hello, I just double checked. There are a total of 583 CT scans that meet the criteria, however, just for sanity check, I added 3 more CT scans randomly (so a total of 583). But for evaluation, only the 583 CT scans were valid

**Comment by czifan** [comment]
Thank you very much!!!
