### ISSUE TITLE
What's the meaning of this result

### ISSUE THREAD

**Issue by Amadeuszhao** [uci-cbcl/NoduleNet#17]
Thank you for sharing your code,I have already finished training and testing procedure and the FROC folder seems normal, However when I tried to visualize the result I counld't figure out the meaning of certain npy files such as 1.3.6.1.4.1.14519.5.2.1.6279.6001.994459772950022352718462251777.npy which was generated  as the test procedure.
The file was all zeros
![image](https://user-images.githubusercontent.com/48089895/76705299-004bce00-671a-11ea-9929-776d14bafcf5.png)
and also where is the segmentaion result I can only find the csv file with columns [seriesuid,coordX,coordY,coorfZ,dizmeter_mm,probability]
Thank you for reading this.

**Comment by LXYTSOS** [comment]
No such file or directory: 'LIDC/preprocessed_test/3/1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028192176989979435275_bboxes.npy'.

I checked my preprocess procedure and I found 1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028192176989979435275.npy in LIDC/annotation/mask_test but I didn't find a match in LIDC/masks_test/{1,2,3,4}.

Did you have the same problem?

**Comment by LXYTSOS** [comment]
how to visualize the result?
