### ISSUE TITLE
can not download

### ISSUE THREAD

**Issue by liudongxu-hu** [uci-cbcl/NoduleNet#18]
Thanks for your sharing.The existing problems is that  the LIDC - IDRI Radiologist Annotations/Segmentations (XML format) can not be downloaded.Can you share through baidu network dish or other way？thank you very much.

**Comment by tanghaotommy** [comment]
[LIDC-XML-only.zip](https://github.com/uci-cbcl/NoduleNet/files/4541075/LIDC-XML-only.zip)

**Comment by liudongxu-hu** [comment]
ok，thank you
