### ISSUE TITLE
Could we download the source code and run now? 

### ISSUE THREAD

**Issue by ShihuaiXu** [uci-cbcl/NoduleNet#2]
thanks for your nice work.

**Comment by tanghaotommy** [comment]
Thanks for your interest and patience. We are working actively on finalizing the source code. The code will be out some time next month and before the MICCAI conference (Oct 13th).

**Comment by ShihuaiXu** [comment]
Hello professor, recently I have to open my topic in my university. My topic is related to Lung nodule segmentation, so I have to run some demo in the LIDC dataset. Could  you send me the source code of your project called nodulenet without finalizing. My email is 531232693@qq.com, thank you very much!

**Comment by tanghaotommy** [comment]
Sorry for the delay and thanks for your interest. We have now made the code public available for non-commercial research purpose only.
