### ISSUE TITLE
Have bug when trying evaluation

### ISSUE THREAD

**Issue by Lijingqin** [uci-cbcl/NoduleNet#23]
training is ok, but, when I trying evaluation, I meet a problem like this:
[Loading model from /home/lijingqin/codes/NoduleNet/results/cross_val_test/model/200.ckpt]
out_dir /home/lijingqin/codes/NoduleNet/results/cross_val_test
Total # of eval data 83
[0] Predicting 1.3.6.1.4.1.14519.5.2.1.6279.6001.603166427542096384265514998412 (281, 234, 306)
Traceback (most recent call last):
  File "test.py", line 114, in eval
    net.forward(input, truth_bboxes, truth_labels, truth_masks, mask)
  File "/home/lijingqin/codes/NoduleNet/net/nodule_net.py", line 390, in forward
    fpr_res = get_probability(self.cfg, self.mode, inputs, self.rpn_proposals,  self.rcnn_logits, self.rcnn_deltas)
  File "/home/lijingqin/NoduleNet-master/NoduleNet-master/env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'NoduleNet' object has no attribute 'rcnn_logits'

and I found the rpn_proposals = 0 and the rpn probability is abnormal.

**Comment by dayan2020** [comment]
> training is ok, but, when I trying evaluation, I meet a problem like this:
> [Loading model from /home/lijingqin/codes/NoduleNet/results/cross_val_test/model/200.ckpt]
> out_dir /home/lijingqin/codes/NoduleNet/results/cross_val_test
> Total # of eval data 83
> [0] Predicting 1.3.6.1.4.1.14519.5.2.1.6279.6001.603166427542096384265514998412 (281, 234, 306)
> Traceback (most recent call last):
> File "test.py", line 114, in eval
> net.forward(input, truth_bboxes, truth_labels, truth_masks, mask)
> File "/home/lijingqin/codes/NoduleNet/net/nodule_net.py", line 390, in forward
> fpr_res = get_probability(self.cfg, self.mode, inputs, self.rpn_proposals, self.rcnn_logits, self.rcnn_deltas)
> File "/home/lijingqin/NoduleNet-master/NoduleNet-master/env/lib/python3.5/site-packages/torch/nn/modules/module.py", line 539, in **getattr**
> type(self).**name**, name))
> AttributeError: 'NoduleNet' object has no attribute 'rcnn_logits'
> 
> and I found the rpn_proposals = 0 and the rpn probability is abnormal.

I have the same problem, how did you solve it

**Comment by dayan2020** [comment]
AttributeError: 'NoduleNet' object has no attribute 'rcnn_logits'
