### ISSUE TITLE
missing codes

### ISSUE THREAD

**Issue by LXYTSOS** [uci-cbcl/NoduleNet#25]
where is display function in visualize.py and average_precision in test.py, and how to visualize the result as gif file?

**Comment by tanghaotommy** [comment]
I have uploaded some utility functions in the util.py. Please see the latest commit. 
For visualization purpose, we first use https://github.com/uci-cbcl/NoduleNet/blob/master/utils/visualize.py#L302 to generate png for each slice. And then use linux command from here https://unix.stackexchange.com/questions/24014/creating-a-gif-animation-from-png-files to convert pngs to gif.

**Comment by joaco18** [comment]
Hi I've noticed that in the function 'utils/util.py/average_precision' the precision is calculated this way: `p = tp / float(tp + fp + fn)`. Is this right? Shouldn't it be `p = tp / float(tp + fp)' instead`?
