### ISSUE TITLE
missing preprocessed_test file when training

### ISSUE THREAD

**Issue by LXYTSOS** [uci-cbcl/NoduleNet#26]
When I tried to train after preprocess I got this error: No such file or directory: 'LIDC/preprocessed_test/3/1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028192176989979435275_bboxes.npy'.

I checked my preprocess procedure and I found 1.3.6.1.4.1.14519.5.2.1.6279.6001.100953483028192176989979435275.npy in LIDC/annotation/mask_test but I didn't find a match in LIDC/masks_test/{1,2,3,4}.

Do you know what may cause this problem?

**Comment by TimothyZero** [comment]
@LXYTSOS hi, LXTSOS, have you solved this problem?

**Comment by LXYTSOS** [comment]
yes, by generating my own train, valid csv file from the preprocessed_test data, I didn't use the split csv files provided by the author.

**Comment by TimothyZero** [comment]
got it. preprocessed_test data may be different because there are some bugs in cvrt_annos_to_npy.
thanks for your reply.

**Comment by DongChen06** [comment]
@LXYTSOS @TimothyZero Could you please give any insights and specific comments on how to change the code to make it work. Thank you so much!
